name: docker-publish

on:
  push:
    branches: 
      - "main"
      - "test"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker tags
        id: set_tags
        run: |
          base_tag="${{ secrets.DOCKER_HUB_USERNAME }}/nq-api"
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "tags=${base_tag}:latest" >> $GITHUB_ENV
          else
            echo "tags=${base_tag}:${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.tags }}
